# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_base_roll_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  left_elbow_lift_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  left_elbow_roll_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  left_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  left_shoulder_roll_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  left_wrist_lift_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  left_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_base_roll_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_elbow_lift_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_elbow_roll_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_shoulder_roll_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_wrist_lift_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  right_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0